---
- name: Installeer Wazuh
  hosts: all
  become: yes

  tasks:
    # Wazuh installatie
    - name: Installeer vereiste pakketten voor Wazuh
      apt:
        name:
          - curl
          - apt-transport-https
          - lsb-release
        state: present

    - name: Voeg Wazuh GPG-sleutel toe
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

    - name: Add Wazuh repository key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
      notify:
        - Update apt cache

    - name: Install Wazuh Agent
      apt:
        name: wazuh-agent
        state: present
        update_cache: yes

    - name: Werk apt-cache bij na toevoegen Wazuh repository
      apt:
        update_cache: yes

    - name: Configure Wazuh Agent to connect to Wazuh Manager
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '.*<address>.*'
        line: '        <address>51.137.208.105</address>'
        insertafter: '<server>'
        create: yes

    - name: Start en activeer Wazuh Manager service
      command: /var/ossec/bin/wazuh-control start

    # Suricata installatie
    - name: Voeg Suricata repository toe
      apt_repository:
        repo: ppa:oisf/suricata-stable
        state: present

    - name: Werk apt-cache bij voor Suricata
      apt:
        update_cache: yes

    - name: Installeer Suricata
      apt:
        name: suricata
        state: present

    - name: Start en activeer Suricata service
      command: /usr/bin/suricata -c /etc/suricata/suricata.yaml
      args:
        chdir: /var/log/suricata

    - name: Werk apt-cache bij
      apt:
        update_cache: yes

    - name: Start Filebeat voor Wazuh logs
      apt:
        name: filebeat
        state: present

    - name: Configureer Filebeat voor Wazuh
      copy:
        src: /etc/filebeat/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'

    - name: Start en schakel Filebeat in
      service:
        name: filebeat
        state: started
        enabled: yes
