---
- name: Installeer Wazuh en Suricata
  hosts: all
  become: yes

  tasks:
    # Wazuh installatie
    - name: Werk apt-cache bij
      apt:
        update_cache: yes

    - name: Installeer vereiste pakketten voor Wazuh
      apt:
        name:
          - curl
          - apt-transport-https
          - lsb-release
        state: present

    - name: Voeg Wazuh GPG-sleutel toe
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

    - name: Add Wazuh repository key
      apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
      notify:
        - Update apt cache

    - name: Install Wazuh Agent
      apt:
        name: wazuh-agent
        state: present
        update_cache: yes

    - name: Werk apt-cache bij na toevoegen Wazuh repository
      apt:
        update_cache: yes

    - name: Configure Wazuh Agent to connect to Wazuh Manager
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '.*<address>.*'
        line: '        <address>51.137.208.105</address>'
        insertafter: '<server>'
        create: yes
        
    - name: Start en activeer Wazuh Agent service
      systemd:
        name: wazuh-agent
        state: started
        enabled: yes

    # Suricata installatie
    - name: Voeg Suricata repository toe
      apt_repository:
        repo: ppa:oisf/suricata-stable
        state: present

    - name: Werk apt-cache bij voor Suricata
      apt:
        update_cache: yes

    - name: Installeer Suricata
      apt:
        name: suricata
        state: present

    - name: Start en activeer Suricata service
      service:
        name: suricata
        state: started
        enabled: yes

    # Elasticsearch installatie
     # Voeg de Elasticsearch GPG-sleutel toe
    - name: Voeg Elasticsearch GPG-sleutel toe
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Voeg Elasticsearch repository toe
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present

    - name: Werk apt-cache bij
      apt:
        update_cache: yes

    - name: Installeer Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Pas configuratie van Elasticsearch aan (discovery.type)
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#discovery.type:'
        line: 'discovery.type: single-node'

    - name: Start en schakel Elasticsearch in
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Installeer Kibana
      apt:
        name: kibana
        state: present

    - name: Configureer Kibana (toegankelijk vanaf alle interfaces)
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server.host:.*'
        line: 'server.host: 0.0.0.0'
        state: present
      notify:
        - Restart Kibana

    - name: Start en schakel Kibana in
      service:
        name: kibana
        state: started
        enabled: yes

    # Wazuh integratie met Elasticsearch
    - name: Maak de map voor Wazuh Elasticsearch template aan
      file:
        path: /var/ossec/integrations/elastic
        state: directory
        mode: '0755'

    - name: Download Wazuh Elasticsearch template
      get_url:
        url: https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json
        dest: /var/ossec/integrations/elastic/elastic-wazuh-template.json
        mode: '0644'
      become: yes

    - name: Voeg Wazuh template toe aan Elasticsearch
      command: >
        curl -X PUT "http://localhost:9200/_template/wazuh"
        -H 'Content-Type: application/json'
        -d @/var/ossec/integrations/elastic/elastic-wazuh-template.json

    - name: Start Filebeat voor Wazuh logs
      apt:
        name: filebeat
        state: present

    - name: Configureer Filebeat voor Wazuh
      copy:
        src: /etc/filebeat/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'

    - name: Start en schakel Filebeat in
      service:
        name: filebeat
        state: started
        enabled: yes

  handlers:
    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state: restarted

    - name: Restart Kibana
      service:
        name: kibana
        state: restarted