---
- name: Installeer Wazuh en Suricata
  hosts: all
  become: yes

  tasks:
    # Wazuh installatie
    - name: Werk apt-cache bij
      apt:
        update_cache: yes

    - name: Installeer vereiste pakketten voor Wazuh
      apt:
        name:
          - curl
          - apt-transport-https
          - lsb-release
        state: present

    - name: Voeg Wazuh GPG-sleutel toe
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

    - name: Voeg Wazuh repository toe
      copy:
        content: "deb https://packages.wazuh.com/4.x/apt/ stable main\n"
        dest: /etc/apt/sources.list.d/wazuh.list

    - name: Werk apt-cache bij na toevoegen Wazuh repository
      apt:
        update_cache: yes

    - name: Installeer Wazuh Manager
      apt:
        name: wazuh-manager
        state: present
        
    - name: Start en activeer Wazuh Agent service
      command: /var/ossec/bin/wazuh-control start

    # Elasticsearch installatie
     # Voeg de Elasticsearch GPG-sleutel toe
    - name: Voeg Elasticsearch GPG-sleutel toe
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Voeg Elasticsearch repository toe
      shell: |
        echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list
      become: true

    - name: Werk apt-cache bij
      apt:
        update_cache: yes

    - name: Installeer Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Pas configuratie van Elasticsearch aan (discovery.type)
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#discovery.type:'
        line: 'discovery.type: single-node'

    - name: Start en schakel Elasticsearch in
      shell: |
        nohup /usr/share/elasticsearch/bin/elasticsearch > /var/log/elasticsearch/elasticsearch.log 2>&1 &
      become: true
      become_user: elasticsearch

    - name: Installeer Kibana
      apt:
        name: kibana
        state: present

    - name: Configureer Kibana (toegankelijk vanaf alle interfaces)
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server.host:.*'
        line: 'server.host: 0.0.0.0'
        state: present
      notify:
        - Restart Kibana

    - name: Start en schakel Kibana in
      command: /usr/share/kibana/bin/kibana
      args:
        chdir: /usr/share/kibana

    # Wazuh integratie met Elasticsearch
    - name: Maak de map voor Wazuh Elasticsearch template aan
      file:
        path: /var/ossec/integrations/elastic
        state: directory
        mode: '0755'

    - name: Download Wazuh Elasticsearch template
      get_url:
        url: https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json
        dest: /var/ossec/integrations/elastic/elastic-wazuh-template.json
        mode: '0644'
      become: yes

    - name: Voeg Wazuh template toe aan Elasticsearch
      command: >
        curl -X PUT "http://localhost:9200/_template/wazuh"
        -H 'Content-Type: application/json'
        -d @/var/ossec/integrations/elastic/elastic-wazuh-template.json

  handlers:
    - name: Restart Elasticsearch
      shell: nohup /usr/share/elasticsearch/bin/elasticsearch > /var/log/elasticsearch.log 2>&1 &
  
    - name: Restart Kibana
      shell: nohup /usr/share/kibana/bin/kibana > /var/log/kibana.log 2>&1 &
